# Generated by Django 2.0.7 on 2018-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='would_recommend',
            field=models.BooleanField(default=True),
        ),
    ]
