# Generated by Django 2.0.7 on 2018-09-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180903_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='negative_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='positive_votes',
            field=models.IntegerField(default=0),
        ),
    ]
